# Define tu propia imagen "onbuild" basada en la imagen Node.js
FROM node:10.24.1 AS onbuild

# Establece el directorio de trabajo en el contenedor
WORKDIR /usr/src/app

# Copia los archivos de tu aplicación al directorio de trabajo
COPY . .

# Instala las dependencias y luego ejecuta npm audit y npm audit fix
RUN npm install

# Expone el puerto en el que tu aplicación se ejecutará
EXPOSE 3000

# Ahora, define una nueva imagen que se basará en tu imagen "onbuild"
FROM onbuild

# Comando para ejecutar tu aplicación
CMD ["node", "server.js"]
