version: '3'
services:
   my-app:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - '3000:3000'
      #volumes:
      #  - ./path/to/your/app:/usr/src/app
      env_file:
         - .env
      environment:
         - NODE_ENV=production
# EJECUTAR: docker-compose up
# DETENER:  docker-compose down

